### ISSUE TITLE
사이드바 검색모달 디테일 수정

### ISSUE THREAD

**Issue by raccoonboy0803** [B08-group-project/outsourcing#16]
## Description
사이드바 검색모달 디테일 수정

## To-Do
- [x] 사이드바 검색 값 페이지 이동해도 유지
- [x] 검색 카테고리 버튼 페이지 이동해도 유지
- [x] 카테고리버튼 선택시 스타일링 변경
- [x] 검색리스트 클릭 시 새탭으로 url이동
- [ ] 사이드바 검색모달 스타일링 작업

## ETC
X

## up-to-date
24.06.19(수)
