### ISSUE TITLE
커스텀 오버레이 마크 생성하기

### ISSUE THREAD

**Issue by tpring** [B08-group-project/outsourcing#19]
## To-Do
- [x] 커스텀 오버레이 마크 UI
- [x] 각 식당을 클릭시 위치 표시
- [x] 오버레이 위치로 지도 이동
