### ISSUE TITLE
커스텀 오버레일 수정 및 css 변경

### ISSUE THREAD

**Issue by tpring** [B08-group-project/outsourcing#31]
## To-Do
- [x] 오버레이 마커가 사라지수있도록 업데이트합니다.
- [x] 사이드 코스 css 수정
- [x] 사이드바 코스 서순 수정이 가능하도록
