### ISSUE TITLE
마이페이지 기능 추가

### ISSUE THREAD

**Issue by SeYoungYee** [B08-group-project/outsourcing#38]
## To-Do
- [x] 저장된 코스 마이페이지에서 확인가능
- [x] 코스가 순서대로 나오도록 수정
- [x] 닉네임 수정 추가
