### ISSUE TITLE
마이페이지 삭제기능+CSS추가

### ISSUE THREAD

**Issue by SeYoungYee** [B08-group-project/outsourcing#50]
## To-Do
- [x] 코스 삭제기능 구현
- [x] CSS추가 ex)삭제버튼 호버 등등
- [x] 코스 삭제 전 물어보는 로직 추가
