### ISSUE TITLE
update 매장 세부 정보 , 사이드 코스구현

### ISSUE THREAD

**Issue by tpring** [B08-group-project/outsourcing#6]
## To-Do
- [x] 사이드바코스 recoil에서 정보 불러와 게시
- [x] recoil 에 저장되어있는 특정 객체 삭제
- [x] 불러와 놓은 데이터를 supabsae에 저장
- [x] 검색rexoil에서 데이터를 받아 매장 세부 정보 항목 표시

###
