### ISSUE TITLE
메인페이지 마커/경로 작업

### ISSUE THREAD

**Issue by 2hanbyeol1** [B08-group-project/outsourcing#7]
## Description
메인 페이지 (지도 ) UI
마커 선 잇기 / 경로 잇기 테스트
장소 검색 사이드바(희진님 작업) 완료 후 마커 및 선 잇기 적용

## To-Do
- [x] 카카오맵 컴포넌트 리팩토링
- [x] 마커 선 잇기 / 경로 잇기 테스트
- [x] 장소 검색 사이드바(희진님 작업) 완료 후 마커 및 선 잇기 적용

## ETC
일단 길찾기? 기능처럼 경로 보여주는거 도전해보고 안 되면 그냥 선으로 잇는 것으로 가겠습니다.

## up-to-date
수요일 저녁까지
